[INCLUDE: common/materials_carpaint.ini]
CarPaintMaterial = "Miata_Skin", "Miata_Skin_1"
DisableDev = 1

; Metallic car paint
[Material_CarPaint_Metallic]
FresnelMax = 1
FresnelC = 0.1
BrightnessAdjustment = 0.8
ColoredSpecular = 0.9
AmbientSpecular = 0.6
AmbientSpecularEXP = 2.5
ClearCoatThickness = 0.06
CarPaintVersionAware = 2
DisableDev = 1

[Material_CarPaint_Chrome]
Materials = Calipers
FresnelMax = 0.8
FresnelC = 0.1
BrightnessAdjustment = 2.0
ColoredSpecular = 0.9
AmbientSpecular = 0.1
AmbientSpecularEXP = 2.5
ClearCoatThickness = 0.4
UseMetallicReflections = 1

[Material_CarPaint_Metallic]
Materials = rim_paint_inner
FresnelMax = 0.085
FresnelC = 0.6
BrightnessAdjustment = 0.65 ; compensates for ambient specular
BaseSpecularColor = 0.2, 0.2, 0.2
SpecularBase = 0.8, 20
AmbientSpecular = 1, 18
SpecularSun = 1, 60
SunMultiplier = 1
ClearCoatThickness = 0.2

[LIGHT_EXTRA_0]
BIND_TO_HEADLIGHTS=0
BIND_TO_EXTRA_D=1
COLOR=0,1,5, 260
DIFFUSE_CONCENTRATION=0.5
EXTERIOR_ONLY=0
INTERIOR_ONLY=0
AFFECTS_TRACK=0
SIMULATE_HEATING= 0.2
LAG=0.19
FADE_AT=90
FADE_SMOOTH=43
MIRROR=0, 0, 0
POSITION=0.4, 0.45, 0.65
DIRECTION=0, -1, 0
RANGE=0.4
RANGE_GRADIENT_OFFSET=0.00
SPECULAR_MULT=-0
SPOT=200

[LIGHT_EXTRA_1]
BIND_TO_HEADLIGHTS=0
BIND_TO_EXTRA_D=1
COLOR=0,1,5, 260
DIFFUSE_CONCENTRATION=0.5
EXTERIOR_ONLY=0
INTERIOR_ONLY=0
AFFECTS_TRACK=0
SIMULATE_HEATING= 0.2
LAG=0.19
FADE_AT=90
FADE_SMOOTH=43
MIRROR=0, 0, 0
POSITION=-0.4,0.45, 0.65
DIRECTION=0, -1, 0
RANGE=0.4
RANGE_GRADIENT_OFFSET=0.00
SPECULAR_MULT=-0
SPOT=200